spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@aiclass_high?TNS_ADMIN=/Users/kimhyunwoo/Project1/Wallet_DB202202180852
    username: admin
    password: Leaf950515!!